---
title: "Sankey plots with R"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r loadPackages}
###=================================================================================
### load in packages
library("dplyr")
library("ggplot2")
library("ggforce")
library("ggalluvial")
library("ggparallel")

```

## Two axes

### Prepare data and specify plot options

```{r prepareDataTwoAxes}
###=================================================================================
### define factor levels to specify order of strata
fct_levels <- c("Labour", "Conservative", "Liberal Democrat", "UKIP", 
                "Brexit Party", "Green Party", "SNP", "Plaid Cymru")

###=================================================================================
### define plot colours
colours <- c("#DC241f", "#0087DC", "#FAA61A", "#70147A", 
            "#12B6CF", "#528D6B", "#FDF38E", "#008142")
names(colours) <- fct_levels

###=================================================================================
### format data
dat_17_19 <- read.csv("sankey_data.csv")

dat_17_19_ggalluvial <- dat_17_19 %>% 
  mutate_at(vars(vote17, vote19),
            funs(factor(., levels = fct_levels)))

dat_17_19_ggforce <- dat_17_19  %>%
  gather_set_data(1:2) %>%
  arrange(x,vote19,desc(vote17)) %>% 
  mutate_at(vars(vote17, vote19, y),
            funs(factor(., levels = fct_levels)))

###=================================================================================
### define plot settings
stratum_width <- 0.3
stratum_font_colour <- "black"
stratum_fill_colour <- "white"
stratum_line_colour <- "black"
stratum_angle <- 0
legend_position <- ""
alpha <- 0.7
```

### ggalluvial

```{r, results='asis',fig.width = 12, fig.height = 7}
ggplot(dat_17_19_ggalluvial,
       aes(y = freq, axis1 = vote17, axis2 = vote19)) +
  geom_alluvium(aes(fill = vote17, color = vote17),
                width = stratum_width, 
                alpha = alpha, 
                knot.pos = 0.4) +
  geom_stratum(width = stratum_width,
               fill = stratum_fill_colour, 
               colour = stratum_line_colour) +
  ggfittext::geom_fit_text(infer.label = TRUE, 
                           stat = "stratum", 
                           width = stratum_width,
                           colour = stratum_font_colour,
                           fontface = "bold",
                           min.size = 3) +
  scale_fill_manual(values = colours) +
  scale_color_manual(values = colours) +
  scale_x_continuous(breaks = 1:2, labels = c("GE vote 2017", "GE vote 2019")) +
  theme_minimal() +
  theme(
    legend.position = legend_position,
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title  = element_blank()
  )
```


### ggforce


```{r, results='asis', fig.width = 10, fig.height = 7}
ggplot(dat_17_19_ggforce, aes(x = x, id = id, split = y, value = freq)) +
  geom_parallel_sets(aes(fill = vote17), 
                     alpha = alpha, 
                     axis.width = stratum_width,
                     n=1000) +
  geom_parallel_sets_axes(axis.width = stratum_width, 
                          fill = stratum_fill_colour,
                          color = stratum_line_colour, 
                          size = 0.3) +
  geom_parallel_sets_labels(colour = stratum_font_colour, 
                            size = 3, 
                            angle = stratum_angle, 
                            fontface="bold") +
  scale_fill_manual(values  = colours) +
  scale_color_manual(values = colours) +
  scale_x_discrete(labels = c("GE vote 2017", "GE vote 2019")) +
  theme_minimal() +
  theme(
    legend.position = legend_position,
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title  = element_blank()
  )
```

## More than two axes

### Prepare data and specify plot options

```{r prepareDataMoreAxes}
###=================================================================================
### define factor levels to specify order of strata
fct_levels_class <- c("1st", "3rd", "2nd", "Crew")
fct_levels_sex <- c("Male", "Female")

###=================================================================================
### format data
dat <- Titanic %>% 
  as.data.frame() %>%
  mutate(Class = factor(Class, levels = fct_levels_class))

dat_plot <- to_lodes_form(as.data.frame(dat),
                                      axes = 1:3,
                                      id = "id")

###=================================================================================
### define plot settings
stratum_width = 0.4
stratum_font_colour = "white"
stratum_fill_colour = "black"
stratum_line_colour = "white"
stratum_angle = 0
legend_position = "right"
alpha <- 0.7
```

### ggalluvial

```{r, results='asis',fig.width = 12, fig.height = 7}
ggplot(dat_plot,
       aes(x = x, stratum = stratum, alluvium = id,
           y = Freq, label = stratum, fill = Survived)) +
  geom_lode(width = stratum_width) +
  geom_flow(width = stratum_width) +
  geom_stratum(width = stratum_width, 
               alpha = 1, 
               fill = stratum_fill_colour, 
               colour = stratum_line_colour) +
  geom_text(stat = "stratum", colour = stratum_font_colour) +
  theme_minimal() +
  theme(
    legend.position = legend_position,
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold")
  )
```


### ggforce


```{r, results='asis', fig.width = 10, fig.height = 7}
ggplot(dat_plot, aes(x = x, id = id, split = stratum, value = Freq)) +
  geom_parallel_sets(aes(fill = Survived), alpha = alpha, axis.width = stratum_width) +
  geom_parallel_sets_axes(axis.width = stratum_width, 
                          fill = stratum_fill_colour,
                          colour = stratum_fill_colour) +
  geom_parallel_sets_labels(colour = stratum_font_colour, angle = stratum_angle) +
  theme_minimal() +
  theme(
    legend.position = legend_position,
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x  = element_blank()
  )

```

